"""The lane map and the branch=hat write guard (.docs/TEAM.md, WP-C).

Why this exists
---------------
The three streams (INFRA / AUTHOR / RESEARCHER) partition the repo's *write*
surfaces, and the branch prefix is the one stateless declaration of which lane a
session is in (TEAM.md, settled principles 1 and 3). Until now that partition was
prompted, not enforced — and "the prompt said don't" is exactly the gap the
orchestrator's no-edit guard exists to close for dispatched roles. This module closes
it for *interactive* sessions: the ownership table lives here as data, and a
PreToolUse hook (``--hook`` mode, wired in ``.claude/settings.json``) consults it on
every Edit/Write, denying out-of-lane writes with the lane and the handoff move
named. The CI stream lint (WP-D) reads the same table, so there is one source of
lane truth, not a hook copy and a CI copy that drift.

Enforcement semantics (settled decision 4): **strict on lane-prefixed branches,
warn-only on ``main`` and other unprefixed branches** — strictness is opt-in by
naming the branch, which every hat does, and the maintainer's own loose sessions stay
unencumbered. The guard is also **fail-open**: it gates Edit/Write file paths it can
positively place inside the repo, and anything it cannot decide (a path outside the
repo, a git failure, malformed hook input) is allowed through — it is
defense-in-depth behind the prompts and code review, not the only wall.

Deliberately stdlib-only: the hook runs on every file edit, and a guard that
imports the schema stack would go down with the very breakage an ``infra/`` session
might be in the middle of fixing.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from .common import ROOT


@dataclass(frozen=True)
class Lane:
    """One stream's write contract: its branch prefix, its hat, and what it may write.

    ``writes`` entries ending in ``/`` are tree prefixes; the rest are exact
    repo-relative files. The list is the TEAM.md ownership table as data — change it
    there and here together, or the contract and the enforcement drift.
    """
    name: str
    prefix: str
    hat: str
    writes: tuple[str, ...]


LANES: dict[str, Lane] = {
    # INFRA owns the machinery and the root-level spine files (the rule-12 crossing
    # set); it never authors content. derived/ is absent on purpose — no lane
    # hand-edits it (see MACHINE_WRITTEN).
    "infra": Lane(
        name="infra", prefix="infra/", hat="/infra",
        writes=(
            "schemas/", "tools/", "tests/", "agents/", ".claude/", ".github/",
            ".docs/", "scripts/",
            "Makefile", "requirements.txt", "README.md", "CLAUDE.md",
            ".gitignore", ".pre-commit-config.yaml", ".schema-version",
        ),
    ),
    # AUTHOR owns the records: canon (via the lifecycle tools), the extraction
    # workflow (plans are human-edited during triage support), and the raw inbox.
    # expositions/ is deliberately absent: apply-only (CLAUDE.md rule 9), and
    # derived/capsules/ regeneration goes through `make build-capsules`, not Edit.
    "author": Lane(
        name="author", prefix="author/", hat="/author",
        writes=("canon/", "extraction/", "raw/"),
    ),
    # RESEARCHER owns raw material and — settled decision 1 — the research code
    # under computations/ (the Computationalist's surface; the comp.* entity that
    # records a script is the Curator's to write). extraction/plans/ is reachable
    # only through `make extract-plan`, so it is not an Edit/Write surface here.
    "research": Lane(
        name="research", prefix="research/", hat="/research",
        writes=("raw/", "computations/"),
    ),
}

# Trees no hand writes, in any lane — the guard denies these on every lane branch
# and explains why, rather than naming a lane to hand off to.
MACHINE_WRITTEN: dict[str, str] = {
    "derived/": (
        "compiled output — regenerated by `make build` (capsules by "
        "`make build-capsules`); if it looks wrong, fix canon/ or tools/ and "
        "rebuild (CLAUDE.md rule 1)"
    ),
    "expositions/": (
        "written only by `make extract-apply` from a human-triaged plan — prose "
        "goes through raw/ and the extraction pipeline (CLAUDE.md rule 9)"
    ),
}


@dataclass(frozen=True)
class Verdict:
    decision: str  # "allow" | "warn" | "deny"
    message: str = ""


def lane_for_branch(branch: str) -> Lane | None:
    """The lane a branch declares, or None for main/detached/unprefixed branches."""
    return next((l for l in LANES.values() if branch.startswith(l.prefix)), None)


def _matches(rel_path: str, entry: str) -> bool:
    return rel_path.startswith(entry) if entry.endswith("/") else rel_path == entry


def owning_lanes(rel_path: str) -> list[Lane]:
    """Every lane whose write surface covers the path (raw/ has two owners)."""
    return [l for l in LANES.values() if any(_matches(rel_path, e) for e in l.writes)]


def _owner_names(owners: list[Lane]) -> str:
    return " or ".join(f"{o.name.upper()} ({o.hat})" for o in owners)


def _owners_phrase(owners: list[Lane]) -> str:
    return (f"It belongs to the {_owner_names(owners)} lane." if owners
            else "No lane owns it.")


def check_write(branch: str, rel_path: str) -> Verdict:
    """Judge one write of ``rel_path`` (repo-relative, posix) on ``branch``.

    Pure and injectable-free so the hook, the WP-D CI lint, and the tests all judge
    with the same function — the enforcement *is* this return value; everything else
    is plumbing.
    """
    lane = lane_for_branch(branch)

    machine = next((reason for prefix, reason in MACHINE_WRITTEN.items()
                    if rel_path.startswith(prefix)), None)
    if machine:
        msg = f"'{rel_path}' is {machine}."
        if lane:
            return Verdict("deny", f"lane guard ({lane.name}): {msg}")
        return Verdict("warn", f"lane note (branch '{branch}' declares no lane): {msg} "
                               "This write would be denied on any lane branch.")

    if lane:
        if any(_matches(rel_path, e) for e in lane.writes):
            return Verdict("allow")
        owners = owning_lanes(rel_path)
        target = owners[0].prefix if owners else "<lane>/"
        return Verdict("deny", (
            f"lane guard: '{rel_path}' is outside the {lane.name.upper()} lane's "
            f"write surface (branch '{branch}'). {_owners_phrase(owners)} "
            f"Handoff move: park or finish this branch and cut a '{target}<topic>' "
            f"branch wearing that hat — or leave a handoff note naming the receiving "
            f"lane (.docs/TEAM.md, 'Jumping lanes')."
        ))

    owners = owning_lanes(rel_path)
    if owners:
        return Verdict("warn", (
            f"lane note (branch '{branch}' declares no lane): '{rel_path}' belongs "
            f"to the {_owner_names(owners)} lane — on a lane-prefixed branch this "
            f"write would be gated mechanically (.docs/TEAM.md)."
        ))
    return Verdict("allow")


# --- the CI stream lint (WP-D) ------------------------------------------------

# What a lane's *PR diff* may contain beyond its Edit/Write surface: tool-written
# trees the lane's own make targets produce and the gate requires committed. This is
# why the lint does not just reuse check_write: the hook judges hand-edits, the lint
# judges committed diffs, and the two differ exactly on machine-written output.
# derived/ is committable from every lane — whichever lane staled it rebuilds and
# commits it (CLAUDE.md rule 5; even a research PR stales derived/indices/tags.json
# by adding a tagged raw file). expositions/ is committable only from the Author
# lane (`make extract-apply` runs there); extraction/plans/ from research via its
# own `make extract-plan` runs.
LANE_COMMITTABLE: dict[str, tuple[str, ...]] = {
    "infra": ("derived/",),
    "author": ("derived/", "expositions/"),
    "research": ("derived/", "extraction/plans/"),
}


@dataclass(frozen=True)
class LintFinding:
    path: str
    message: str


def lint_diff(branch: str, paths) -> tuple[list[LintFinding], str]:
    """Judge a PR's changed paths against its branch's declared lane.

    Returns ``(findings, note)``: one finding per lane-crossing path, each naming
    both lanes and the split move; ``note`` carries the no-lane explanation when the
    branch is unprefixed (decision 4: those stay unencumbered, so the lint skips
    rather than guessing a lane from the diff).
    """
    lane = lane_for_branch(branch)
    if lane is None:
        return [], (f"stream lint: branch '{branch}' declares no lane prefix — "
                    "skipped (unprefixed branches are unencumbered; .docs/TEAM.md).")
    allowed = lane.writes + LANE_COMMITTABLE[lane.name]
    findings = []
    for path in sorted(set(paths)):
        if any(_matches(path, e) for e in allowed):
            continue
        owners = owning_lanes(path)
        target = owners[0].prefix if owners else "<lane>/"
        findings.append(LintFinding(path, (
            f"PR from '{branch}' ({lane.name.upper()} lane) touches '{path}' — "
            f"{_owners_phrase(owners)} Split this PR: keep {lane.name.upper()}-lane "
            f"changes on this branch and move '{path}' to a '{target}<topic>' branch."
        )))
    return findings, ""


def changed_paths(base: str, *, root: Path = ROOT, run=None) -> list[str]:
    """Paths a PR changes relative to ``base`` (merge-base diff, so only the PR's own
    commits count — not what base gained since the branch point)."""
    _run = run or subprocess.run
    result = _run(["git", "diff", "--name-only", f"{base}...HEAD"],
                  cwd=str(root), capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError((result.stderr or "").strip() or "git diff failed")
    return [line.strip() for line in (result.stdout or "").splitlines() if line.strip()]


# --- plumbing: branch discovery and the PreToolUse hook -----------------------

def current_branch(root: Path = ROOT, run=None) -> str:
    """The checked-out branch name, or "" (detached HEAD / not a repo) — unprefixed."""
    _run = run or subprocess.run
    try:
        result = _run(["git", "branch", "--show-current"], cwd=str(root),
                      capture_output=True, text=True)
    except OSError:
        return ""
    return (result.stdout or "").strip()


def hook_response(payload: dict, *, root: Path = ROOT, branch: str | None = None) -> dict:
    """Turn one PreToolUse payload into the hook's JSON response (empty = allow).

    Only ``file_path``/``notebook_path`` writes inside the repo are judged; anything
    else — a scratchpad file, a payload shape this version doesn't know — falls
    through to allow, per the fail-open contract in the module docstring. A deny is
    returned as a ``permissionDecision`` (the mechanical block, with the reason shown
    to the model so it makes the handoff move instead of retrying); a warn rides
    ``systemMessage``, visible to the human and blocking nothing.
    """
    tool_input = payload.get("tool_input") or {}
    raw = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
    if not raw:
        return {}
    path = Path(raw)
    if not path.is_absolute():
        path = Path(payload.get("cwd") or root) / path
    try:
        rel = path.resolve().relative_to(Path(root).resolve()).as_posix()
    except ValueError:
        return {}  # outside the repo — not this guard's business

    verdict = check_write(branch if branch is not None else current_branch(root), rel)
    if verdict.decision == "deny":
        return {"hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": verdict.message,
        }}
    if verdict.decision == "warn":
        return {"systemMessage": verdict.message}
    return {}


def main(argv: list[str] | None = None, stdin=None) -> int:
    ap = argparse.ArgumentParser(
        description="Lane write guard: judge a write against the branch's lane.")
    ap.add_argument("--hook", action="store_true",
                    help="PreToolUse mode: read the hook payload JSON on stdin, "
                         "emit the response JSON on stdout, always exit 0")
    ap.add_argument("--branch", help="branch to judge as (default: the checked-out one)")
    ap.add_argument("--path", help="repo-relative path to judge (non-hook mode)")
    ap.add_argument("--lint", action="store_true",
                    help="CI stream lint: judge a PR's whole diff against the "
                         "branch's lane (WP-D); advisory unless --strict")
    ap.add_argument("--base", default="origin/main",
                    help="lint mode: diff base ref (default: origin/main)")
    ap.add_argument("--strict", action="store_true",
                    help="lint mode: exit 1 on findings instead of 0 (advisory)")
    ap.add_argument("paths", nargs="*",
                    help="lint mode: judge these paths instead of the git diff")
    args = ap.parse_args(argv)

    if args.hook:
        # Fail-open end to end: a malformed payload or an internal error must never
        # turn the guard into a wall in front of unrelated work.
        try:
            payload = json.load(stdin or sys.stdin)
            response = hook_response(payload, branch=args.branch)
        except Exception as exc:  # noqa: BLE001 — deliberate catch-all, see above
            print(f"lanes hook error (allowing write): {exc}", file=sys.stderr)
            return 0
        if response:
            print(json.dumps(response))
        return 0

    if args.lint:
        branch = args.branch if args.branch is not None else current_branch()
        findings, note = lint_diff(branch, args.paths or changed_paths(args.base))
        if note:
            print(note)
            return 0
        for f in findings:
            # ::warning is GitHub's advisory annotation syntax — surfaced on the PR
            # checks UI without failing the step; harmless plain text elsewhere.
            print(f"::warning file={f.path}::{f.message}")
        if findings:
            print(f"\nstream lint: {len(findings)} lane-crossing path(s) on "
                  f"'{branch}' — see warnings above (.docs/TEAM.md, WP-D).")
            return 1 if args.strict else 0
        print(f"stream lint: clean — every changed path is in the "
              f"'{branch}' lane's surface.")
        return 0

    if not args.path:
        ap.error("--path is required outside --hook/--lint mode")
    branch = args.branch if args.branch is not None else current_branch()
    verdict = check_write(branch, args.path)
    print(f"{verdict.decision}: {verdict.message}" if verdict.message else verdict.decision)
    return 2 if verdict.decision == "deny" else 0


if __name__ == "__main__":
    sys.exit(main())
